name: Stage

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Change directory
        run: cd ./client

      - name: Prepare node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies and lint
        run: yarn ci && yarn lint