name: Stage

on:
  push:
    branches: [ develop ]
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Prepare node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        working-directory: ./client
        run: yarn ci

  linting:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - run: ls
      - name: Lint
        working-directory: ./client
        run: yarn lint

  test:
    needs: prepare
    runs-on: ubuntu-latest
    steps:
      - name: Run unit tests
        working-directory: ./client
        run: yarn test